### ISSUE TITLE
Seamless Transaction Module for Opencart

### ISSUE THREAD

**Issue by kapeel45** [razorpay/razorpay-opencart#5]
Do you guys have another module called seamless or this is the only module to take through payment process?

**Comment by captn3m0** [comment]
Can you explain what you mean by seamless? Our payment process is entirely in the merchant website, with zero redirects.

**Comment by kapeel45** [comment]
inserting the card number and CVV details built in to Merchant page

**Comment by kapeel45** [comment]
For example refer below link to take a demo wrt seamless transaction

http://demo.xtensions.in/payu/2/

**Comment by captn3m0** [comment]
No, we do not have any plans for the same, since it becomes really harder to ensure PCI compliance.

For eg, in the link you gave, some of the card details are getting submitted to the merchant website (cvv and expiry). This would require auditing the merchant website, and as such is very likely against the PCI guidelines.

Our checkout flow, on the other hand, allows a customer to complete the entire payment within the same merchant website (and there are no redirects).

**Comment by kapeel45** [comment]
Ok Thanks for the Info.
