### ISSUE TITLE
Always capturing Rs 199 for payment

### ISSUE THREAD

**Issue by rajanrathi1987** [razorpay/razorpay-opencart#56]
![image](https://user-images.githubusercontent.com/78319525/118396720-601b6d00-b66e-11eb-8fda-05639a2ab462.png)

**Comment by cartbinder** [comment]
@rajanrathi1987 Are you using any kind of one page checkout?

**Comment by rajanrathi1987** [comment]
I am using Journal 3 theme

**Comment by cartbinder** [comment]
The issue is because of the one-page checkout which does not send the new value or Razorpay cache the order total and displays the same for one order id. Please try the solution below:

For journal3, there can be one workaround.
Go to journal3 - skins - checkout - journal - advanced.
And enable 2 step payment for Razorpay. See the link below:
https://www.awesomescreenshot.com/image/8289329?key=3c002095d8e395625d78193ea02baab8

**Comment by rajanrathi1987** [comment]
Thanks I will try and confirm

**Comment by rajanrathi1987** [comment]
Thanks it fixed the problem
